version: "3"
services:
  web:
    # image: kirkpig/zinusoidal-frontend:latest"
    build: ./frontend
    ports:
      - 80:80
      - 443:443
    # Secret only for deployment (HTTPS)
    # volumes:
      # - /home/ubuntu/ssl:/etc/nginx/certs
  logic:
    # NOTE: Before build please setup your system in ./backend/config.yml
    # image: kirkpig/zinusoidal-backend:latest
    build: ./backend
    ports:
      - 1323:1323
    # Secret only for deployment (firebase database)
    # volumes:
      # - /home/ubuntu/backend_secret:/etc/zinusoidal/secret 