app:
  port: 1323
mysql:
  host: 127.0.0.1
  port: 3306
  username: ""
  password: ""
  db_name: "fortune_db"
  net: "tcp"

smtp:
  host: "smtp.gmail.com"
  ip: 192.168.1.10
  port: 335
email:
  email: "xxx@gmail.com"
  password: "xxx"
