app:
  port: 1323
mysql:
  host: 127.0.0.1
  port: 3306
  username: "fortune_user"
  password: "123456"
  db_name: "fortune168"
  net: "tcp"
smtp:
  host: "smtp.gmail.com"
  port: 587
email:
  email: "vipsnam927@gmail.com"
  password: "Namning2793"
bucket:
  zone: ""
  access: ""
  secret: ""
  name: ""
