app:
  port: 1323
mysql:
  host: 127.0.0.1
  port: 3306
  username: ""
  password: ""
  db_name: ""
  net: ""
smtp:
  host: "smtp.gmail.com"
  port: 587
email:
  email: ""
  password: ""
bucket:
  zone: ""
  access: ""
  secret: ""
  name: ""
firebase_secret:
  type: ""
  project_id: ""
  private_key_id: ""
  private_key: ""
  client_email": ""
  client_id: ""
  auth_uri: ""
  token_uri: ""
  auth_provider_x509_cert_url: ""
  client_x509_cert_url: ""