name: "[Development] Deployment: Build image and deploy to AWS"

on:
  push:
    branches: [ dev ]

jobs:
  docker-backend:
    name: "Build and push backend image to ghcr.io"
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Get in to backend folder
        run: |-
          cd backend
      - 
        name: Log in to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ format('ghcr.io/{0}-backend:latest', github.repository) }}
  docker-frontend:
    name: "Build and push frontend image to ghcr.io"
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Get in to frontend folder
        run: |-
          cd frontend
      - 
        name: Log in to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ format('ghcr.io/{0}-frontend:latest', github.repository) }}